name: build_my_app

on: push

jobs:
  build:
    name: Build our App
    runs-on: ubuntu-latest
    steps:
      - name: "Pull Code"
       - uses: actions/checkout@v2
       - run : pwd
       - run : ls